# This file holds the configurations train a normalizing flow by the main.py file
# You can set multiple configurations and the main file will loop trough them and perform diferent trainings

configuration_2023_test_v3:
    n_transforms    : 6
    aux_nodes       : 128
    aux_layers      : 2
    n_splines_bins  : 8
    initial_lr      : 1.0e-3
    batch_size      : 512
    max_epochs      : 75
    DoKinematicsRW  : True
    IsAutoRegressive: False








