# This file holds the configurations train a normalizing flow by the main.py file
# You can set multiple configurations and the main file will loop trough them and perform diferent trainings

configuration_2023_test_repo_merge:
    n_transforms    : 5
    aux_nodes       : 128
    aux_layers      : 2
    n_splines_bins  : 10
    initial_lr      : 1.0e-4
    batch_size      : 4096
    max_epochs      : 25
    DoKinematicsRW  : True
    IsAutoRegressive: False











