#Specify any required software, devices or machines
requirements = (Machine == "lx3agpu2.physik.rwth-aachen.de")

executable     = flow.sh

log            = flow_NSF_Iso_High_stats.log
output         = flow_NSF_Iso_High_Stats.out
error          = flow_NSF_Iso_High_Stats.err

output = flow.out$(Process)

transfer_input_files = main.py,flo_configuration.yaml

request_cpus   = 4
request_memory = 50000

request_GPUs   = 1

queue
